site_name: Project Nassau - Smoking Gun
version: 0.2.3
site_url: https://rickhallett.github.io/smoking-gun/
repo_url: https://github.com/rickhallett/smoking-gun
theme:
  name: terminal
  # palette: gruvbox_dark
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
plugins:
  - search
  - pdf-export:
      combined: true
      combined_output_path: manual.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
extra:
  social: []
  generator: false
extra_css:
  - assets/stylesheets/extra.css
# Omit 'nav' to auto-generate from docs/ folder hierarchy
